name: UI tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose tests
        required: true
        type: choice
        options:
          - All tests
          - Smoke tests
          - Functional tests

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"
      - name: All tests
        if: "github.event.inputs.deployment_target == 'All tests'"
        env:
          LOGIN: ${{ secrets.LOGIN }}
          REG_EMAIL: ${{ secrets.REG_EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: pytest --alluredir=allure-results
        continue-on-error: true
      - name: Smoke tests
        if: "github.event.inputs.deployment_target == 'Smoke tests'"
        env:
          LOGIN: ${{ secrets.LOGIN }}
          REG_EMAIL: ${{ secrets.REG_EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: pytest -m smoke --alluredir=allure-results
        continue-on-error: true
      - name: Functional tests
        if: "github.event.inputs.deployment_target == 'Functional tests'"
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: pytest -m functional --alluredir=allure-results
        continue-on-error: true
      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  publish-report:
    needs: ui-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results
      - name: Build Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history